name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Check Compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build library
        run: cargo build --verbose

      - name: Check compilation
        run: cargo check --verbose

      - name: Run tests
        run: cargo test --all --verbose

      - name: Run clippy (lints)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build documentation
        run: cargo doc --no-deps --all-features --document-private-items
